# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c2da2d00692141f39db71a170b1f3f8ad4aee56221750eaf08947960a6a994ba797d72de74376db1c852b94a2d72c6a4b1178d22f66fb75defa64549b3203df

test:
  secret_key_base: ea05157026bd79152e28ec3253da462fc58236eaaeec691fe0fd1eda3b0aac1a827efe12d9f6cf08de688a2239c6aafa9315c739ca0e9a2145b2c1d780fe8200

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
